import streamlit as st
import plotly.graph_objects as go
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# --- THEME & BRANDING ---
BRAND_RED = "#e94560"
BRAND_BLUE = "#0f3460"
BRAND_ORANGE = "#e67e22"
BRAND_GREEN = "#27ae60"
BG_DARK = "#0a0a0a"
CARD_BG = "#141414"

st.set_page_config(page_title="Odyssey AI Readiness", layout="centered")

# Custom CSS
st.markdown(f"""
    <style>
    .stApp {{ background-color: {BG_DARK}; color: white; }}
    .stButton>button {{ background-color: {BRAND_RED}; color: white; border-radius: 8px; width: 100%; height: 3em; font-weight: bold; border: none; }}
    div[data-testid="stExpander"] {{ background-color: {CARD_BG}; border: 1px solid #2a2a2a; border-radius: 12px; }}
    .stRadio>label {{ color: #bbb !important; }}
    </style>
    """, unsafe_allow_html=True)

# --- EMAIL FUNCTION ---
def send_email(to_email, user_name, school_name, scores, plan_text):
    # This pulls your email credentials from "Secrets" (Step 2 below)
    try:
        msg = MIMEMultipart()
        msg['From'] = st.secrets["email_user"]
        msg['To'] = f"{to_email}, {st.secrets['admin_email']}" # Sends to user AND you
        msg['Subject'] = f"🛡️ AI Action Plan: {school_name}"

        body = f"Hello {user_name},\n\nHere is your 90-Day AI Action Plan for {school_name}.\n\n"
        body += f"READINESS SCORES:\n{scores}\n\n"
        body += f"YOUR COMMITMENTS:\n{plan_text}\n\n"
        body += "Generated by Odyssey Learning Solutions."
        
        msg.attach(MIMEText(body, 'plain'))
        
        server = smtplib.SMTP(st.secrets["email_host"], st.secrets["email_port"])
        server.starttls()
        server.login(st.secrets["email_user"], st.secrets["email_password"])
        server.send_message(msg)
        server.quit()
        return True
    except Exception as e:
        st.error(f"Email failed: {e}")
        return False

# --- HEADER ---
st.title("🛡️ 90-Day AI Action Plan")
st.caption("Odyssey Learning Solutions | AI Readiness Assessment")

# --- STEP 1: CONTACT DETAILS ---
col1, col2 = st.columns(2)
with col1:
    name = st.text_input("Full Name")
    school = st.text_input("School / Trust")
with col2:
    email = st.text_input("Email Address")
    role = st.text_input("Role")

consent = st.checkbox("I consent to receiving my action plan and follow-up AI resources via email.", value=True)

st.divider()

# --- STEP 2: ASSESSMENT (5 Questions Per Pillar) ---
score_map = {"No": 0, "In development": 1, "Yes but needs updating": 2, "Yes and current": 3,
             "Not sure": 0, "Partially": 1, "Aware but not done": 1, "In progress": 2, "Complete": 3,
             "No idea": 0, "Some awareness": 1, "Mostly": 2, "Full visibility": 3,
             "Planning one": 1, "Yes, maintained": 3, "None": 0, "Self-directed only": 1,
             "Some formal CPD": 2, "Structured programme": 3, "Definitely not": 0, 
             "Probably not": 1, "Confidently yes": 3, "Informally": 1, "Partially documented": 2, "Fully documented": 3}

tab1, tab2, tab3, tab4 = st.tabs(["Policy", "Process", "People", "Proof"])

with tab1:
    st.subheader("Policy Questions")
    p1 = st.radio("Formal AI use policy?", ["No", "In development", "Yes and current"])
    p2 = st.radio("AI in safeguarding policy?", ["No", "Partially", "Yes"])
    p3 = st.radio("Assessment/Malpractice policy updated?", ["No", "In progress", "Complete"])
    p4 = st.radio("Parental AI consent process established?", ["No", "Planning", "Yes"])
    p5 = st.radio("Board/Governor level AI strategy?", ["No", "Informal", "Formalized"])
    score_policy = (score_map.get(p1,0)+score_map.get(p2,0)+score_map.get(p3,0)+score_map.get(p4,0)+score_map.get(p5,0))/5

with tab2:
    st.subheader("Process Questions")
    r1 = st.radio("Awareness of staff AI tool use?", ["No idea", "Some awareness", "Full visibility"])
    r2 = st.radio("Register of approved AI tools?", ["No", "Partial", "Yes, maintained"])
    r3 = st.radio("DPIAs completed for AI tools?", ["No", "For some", "Yes, for all"])
    r4 = st.radio("Feedback loop for staff using AI?", ["No", "Informal", "Regularly scheduled"])
    r5 = st.radio("Procurement process includes AI vetting?", ["No", "Sometimes", "Always"])
    score_process = (score_map.get(r1,0)+score_map.get(r2,0)+score_map.get(r3,0)+score_map.get(r4,0)+score_map.get(r5,0))/5

with tab3:
    st.subheader("People Questions")
    l1 = st.radio("Named person leading AI?", ["No", "Informally", "Yes with dedicated time"])
    l2 = st.radio("Staff received formal AI training?", ["None", "Some CPD", "Structured programme"])
    l3 = st.radio("AI Working Group/Champions established?", ["No", "A few staff", "Formal group"])
    l4 = st.radio("Parental engagement/comms on AI?", ["None", "Planned", "Active"])
    l5 = st.radio("Student AI Literacy lessons?", ["No", "Ad-hoc", "Systematic"])
    score_people = (score_map.get(l1,0)+score_map.get(l2,0)+score_map.get(l3,0)+score_map.get(l4,0)+score_map.get(l5,0))/5

with tab4:
    st.subheader("Proof Questions")
    v1 = st.radio("Log of AI training completion?", ["No", "Informal", "Systematic"])
    v2 = st.radio("Documentation of tool approval decisions?", ["No", "Some", "Fully documented"])
    v3 = st.radio("Evidence AI governance to governors?", ["Definitely not", "Partially", "Confidently yes"])
    v4 = st.radio("Biannual AI use surveys (Staff/Students)?", ["No", "Planned", "Active"])
    v5 = st.radio("Case studies of impact documented?", ["No", "A few", "Embedded"])
    score_proof = (score_map.get(v1,0)+score_map.get(v2,0)+score_map.get(v3,0)+score_map.get(v4,0)+score_map.get(v5,0))/5

# --- GENERATE PLAN ---
if st.button("GENERATE MY 90-DAY PLAN"):
    if not name or not email or not consent:
        st.error("Please provide your name, email, and consent to receive the plan.")
    else:
        # Chart
        categories = ['Policy', 'Process', 'People', 'Proof']
        scores = [score_policy, score_process, score_people, score_proof]
        
        fig = go.Figure()
        fig.add_trace(go.Scatterpolar(r=scores + [scores[0]], theta=categories + [categories[0]], fill='toself', line_color=BRAND_RED))
        fig.update_layout(polar=dict(radialaxis=dict(visible=True, range=[0, 3])), paper_bgcolor=BG_DARK, font_color="white", showlegend=False)
        st.plotly_chart(fig, use_container_width=True)
        
        # Build Plan Text for Email
        plan_text = ""
        st.header("🎯 Your 90-Day Commitments")
        
        with st.expander("📝 Policy Actions", expanded=(score_policy < 2)):
            txt = "- Draft standalone AI policy.\n- Reference AI in Safeguarding.\n- Update Malpractice definitions."
            st.write(txt); plan_text += f"\nPolicy:\n{txt}"
        
        with st.expander("⚙️ Process Actions", expanded=(score_process < 2)):
            txt = "- Audit tool use.\n- Complete DPIAs for core tools.\n- Setup AI Tool Register."
            st.write(txt); plan_text += f"\nProcess:\n{txt}"
            
        with st.expander("👥 People Actions", expanded=(score_people < 2)):
            txt = "- Appoint AI Lead.\n- Launch AI Working Group.\n- Deliver Staff CPD."
            st.write(txt); plan_text += f"\nPeople:\n{txt}"
            
        with st.expander("✅ Proof Actions", expanded=(score_proof < 2)):
            txt = "- Log training records.\n- Document impact case studies.\n- Report to Governors."
            st.write(txt); plan_text += f"\nProof:\n{txt}"

        # Send Email
        score_summary = f"Policy: {score_policy}/3, Process: {score_process}/3, People: {score_people}/3, Proof: {score_proof}/3"
        success = send_email(email, name, school, score_summary, plan_text)
        if success:
            st.success(f"Excellent, {name}. Your plan has been emailed to {email}!")
